### ISSUE TITLE
Create Models and typeDefs / resolvers

### ISSUE THREAD

**Issue by 1alyciaoliveira** [1alyciaoliveira/JobApplicationTracker#4]
- [x] Models
- [x] #15

**Comment by AlexTrejo92** [comment]
Created DB-Structure-Models branch from Main, submitted PR and approved, basic structure of Models created

**Comment by MariaFernandaMarroquin** [comment]
Models created, typeDefs and resolvers (Alex)
Update in typeDefs and resolvers, just pending the token function in adduser and login mutations (Fer)
